### ISSUE TITLE
you girlfriend is a bitch

### ISSUE THREAD

**Issue by lifeofsarah** [e10jon/coderintros#1]
seriously. that chick needs to relax  . 

ps sorry i dont know if everyone can read this or just you can. i dont know how to delete it. sorry bae

**Comment by davegrice** [comment]
Seems legit...

**Comment by e10jc** [comment]
@lifeofsarah i've reviewed your request and i'll start working on a fix. i'll ping you when it's ready.

**Comment by lifeofsarah** [comment]
what does?
